swagger: 2
info:
  title: Simblog API
  description: Simple blog API
  version: "1.0.0"
host: "localhost:8080"
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /user:
    get:
      description: "Returns list of all users"
      operationId: "getUsers"
      responses:
        default:
          schema:
            $ref: GetUsersResponse
    post:
      description: "Add user"
      operationId: "addUser"
      parameters:
        - name: addUserRequest
          in: body
          required: true
          schema:
            $ref: AddUserRequest
      responses:
        default:
          schema:
            $ref: AddUserResponse
  /user/{id}:
    get:
      description: "Returns user by id"
      operationId: "getUser"
      parameters:
        - name: id
          in: path
          type: integer
          format: int64
          required: false
      responses:
        default:
          schema:
            $ref: GetUserResponse
definitions:
  User:
    required:
      - id
      - username
      - enabled
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      enabled:
        type: boolean
  GenericResponse:
    required:
      - status
    properties:
      status:
        type: boolean
  GetUsersResponse:
    allOf:
      - $ref: GenericResponse
      - type: object
        required:
          - status
        properties:
          users:
            type: array
            items:
              $ref: User
  GetUserResponse:
    allOf:
      - $ref: GenericResponse
      - type: object
        properties:
          user:
            $ref: User
  AddUserRequest:
    required:
      - username
      - password
    properties:
      username:
        type: string
      password:
        type: string
  AddUserResponse:
    allOf:
      - $ref: GenericResponse
      - type: object
        properties:
          user:
            $ref: User
            