DO
$$
BEGIN
IF NOT EXISTS (SELECT COLUMN_NAME
               FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
                 AND UPPER(TABLE_NAME) = 'SIMBLOG_USER'
                 AND UPPER(COLUMN_NAME) = 'ENABLED')
THEN
  ALTER TABLE SIMBLOG_USER
    ADD COLUMN ENABLED BOOLEAN;
  UPDATE SIMBLOG_USER
    SET ENABLED = TRUE;
  ALTER TABLE SIMBLOG_USER
    ALTER COLUMN ENABLED SET NOT NULL;
ELSE
  RAISE NOTICE 'Column SIMLOG_USER.ENABLED already exists';
END IF;
END$$;
