DO
$$
BEGIN
IF NOT EXISTS (SELECT COLUMN_NAME
               FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = CURRENT_SCHEMA()
                 AND UPPER(TABLE_NAME) = 'SIMBLOG_USER_ROLE')
THEN
  CREATE TABLE SIMBLOG_USER_ROLE (
    USER_ID BIGINT,
    USER_ROLE VARCHAR(255),
    CONSTRAINT SIMBLOG_USER_ROLE_PK PRIMARY KEY (USER_ID, USER_ROLE),
    CONSTRAINT SIMBLOG_USER_FK FOREIGN KEY (USER_ID) REFERENCES SIMBLOG_USER(ID)
  );
ELSE
  RAISE NOTICE 'Table SIMLOG_USER_ROLE already exists';
END IF;
END$$;
